query: select vw_asset_locations.location_code,vw_asset_locations.location_type_code,vw_asset_locations.location_maximum_units, vw_asset_locations.asset_number,vw_asset_locations.location_quantity,vw_asset_locations.description,vw_asset_locations_fullbins.full_bin_qty, 'row ' || CAST(ROW_NUMBER() OVER() AS character varying) AS id  from vw_asset_locations left join vw_asset_locations_fullbins on vw_asset_locations.asset_number = vw_asset_locations_fullbins.asset_number and vw_asset_locations.location_code = vw_asset_locations_fullbins.farm_code  WHERE (vw_asset_locations.location_code={vw_asset_locations.location_code} AND  vw_asset_locations.location_type_code={vw_asset_locations.location_type_code} AND vw_asset_locations.asset_number={vw_asset_locations.asset_number})  order by vw_asset_locations.location_code
main_table_name: locations
fields:
 field1:
  field_name: vw_asset_locations.location_code
  caption: location_code
  field_type: text
 field2:
  field_name: vw_asset_locationslocation_type_code
  caption: location_type_code
  field_type: lookup
  list: "select location_type_code from location_types order by location_type_code asc"
 field3:
  field_name: vw_asset_locations.asset_number
  caption: asset_number
  field_type: lookup
  list: "select asset_number from asset_items order by asset_number asc"

