query: SELECT location_code, stock_qty, locn_qty, comparison from vw_compare_units_in_location WHERE (location_code={location_code} and comparison={comparison})
main_table_name: locations
fields:
 field1:
  field_name: location_code
  caption: location_code
  field_type: lookup
  list: "select location_code from locations order by location_code asc"
 field2:
  field_name:  comparison
  caption: comparison
  field_type: lookup
  list: "select distinct status_code from statuses where status_type_code = 'comparison' order by status_code"