query: SELECT trans_date, current_location, stand_time_hours, previous_trans_date_time, location_from, location_to, transaction_business_name, pallet_number, stock_type_code, season_code, iso_week_code, commodity_code, marketing_variety_code, fg_code_old, created_on, updated_at, destroyed, date_time_completed, rw_create_datetime, inspection_date_time, age_inspect, inspection_level_code, inspection_reason, process_status, qc_result_status, date_time_created, carton_quantity_actual, qc_status_code, oldest_pack_date_time, age_interwarehouse, last_interwarehouse_offload_date, 'row ' || CAST(ROW_NUMBER() OVER() AS character varying) AS id  FROM vwinventory_stock_status_pallet WHERE (vwinventory_stock_status_pallet.stock_type_code={vwinventory_stock_status_pallet.stock_type_code} and vwinventory_stock_status_pallet.pallet_number={vwinventory_stock_status_pallet.pallet_number} and vwinventory_stock_status_pallet.previous_location={vwinventory_stock_status_pallet.previous_location} and vwinventory_stock_status_pallet.location_code={vwinventory_stock_status_pallet.location_code} and vwinventory_stock_status_pallet.standing_hours={vwinventory_stock_status_pallet.standing_hours} and vwinventory_stock_status_pallet.stock_status={vwinventory_stock_status_pallet.stock_status} and  vwonstock_pallets.season_code={vwonstock_pallets.season_code} and vwonstock_pallets.commodity_code={vwonstock_pallets.commodity_code} and vwonstock_pallets.marketing_variety_code={vwonstock_pallets.marketing_variety_code})
main_table_name: inventory_transaction_stocks
fields:
 field1:
  field_name:  vwinventory_stock_status_pallet.stock_type_code
  caption: stock_type_code
  field_type: lookup
  list: "select distinct stock_type_code from stock_types order by stock_type_code"
 field2:
  field_name: vwinventory_stock_status_pallet.previous_location
  caption: previous_location
  field_type: lookup
  list: "select location_code from locations order by location_code"    
 field3:
  field_name: vwinventory_stock_status_pallet.location_code
  caption: current_location
  field_type: lookup
  list: "select location_code from locations order by location_code"    
 field4:
  field_name: vwinventory_stock_status_pallet.stock_status
  caption: stock_status
  field_type: lookup
  list: "select 'NOT_ON_STOCK' as stock_status union select 'ON_STOCK' as stock_status"  
 field5:
  field_name: vwonstock_pallets.season_code
  caption: season
  field_type: lookup
  list: "select distinct season from seasons order by season desc"  
 field6:
  field_name: vwonstock_pallets.commodity_code
  caption: commodity
  field_type: lookup
  list: "select commodity_code from commodities order by commodity_code"    
 field7:
  field_name: vwonstock_pallets.marketing_variety_code
  caption: variety
  field_type: lookup
  list: "select marketing_variety_code from marketing_varieties  order by marketing_variety_code"      
grid_configs:
  column_widths:
  data_types:
    carton_quantity_actual: integer
    age_inspect: integer
    age_interwarehouse: integer
    standing_hours: integer
    between_move_hours: integer
  
  column_captions:
    created_on: first_iw_offload
    updated_at: last_iventory_tran
    carton_quantity_actual: ctn_qty
    date_time_completed: skip_complete
    rw_create_datetime: create_in_reworks
    date_time_created: first_ctn_skip
    last_interwarehouse_offload_date: last_iw_offload