query: select inventory_reference, stock_type_code, location_code, created_on, updated_at, previous_location, destroyed, standing_hours, between_move_hours, stock_status,  'row ' || CAST(ROW_NUMBER() OVER() AS character varying) AS id  from vwinventory_status WHERE (stock_type_code={stock_type_code} and inventory_reference={inventory_reference} and previous_location={previous_location} and location_code={location_code} and standing_hours={standing_hours} and stock_status={stock_status})
main_table_name: stock_items
fields:
 field1:
  field_name:  stock_type_code
  caption: stock_type_code
  field_type: lookup
  list: "select distinct stock_type_code from stock_types order by stock_type_code"
 field2:
  field_name: previous_location
  caption: previous_location
  field_type: lookup
  list: "select location_code from locations order by location_code"    
 field4:
  field_name: location_code
  caption: current_location
  field_type: lookup
  list: "select location_code from locations order by location_code"    
 field5:
  field_name: stock_status
  caption: stock_status
  field_type: lookup
  list: "select 'NOT_ON_STOCK' as stock_status union select 'ON_STOCK' as stock_status"  