query: select  vwinventory_status.inventory_reference,  vwinventory_status.stock_type_code,  vwinventory_status.location_code, vwinventory_status.created_on,  vwinventory_status.updated_at,  vwinventory_status.previous_location,  vwinventory_status.standing_hours,  vwinventory_status.destroyed,  vwinventory_status.between_move_hours,  vwinventory_status.stock_status,  vwbins.rmt_product_code,  vwbins.farm_code,  vwbins.season,  vwbins.track_slms_indicator_1_code,  vwbins.track_slms_indicator_2_code,  vwinventory_status.id from vwinventory_status inner join vwbins on inventory_reference=bin_number WHERE (vwinventory_status.stock_type_code={vwinventory_status.stock_type_code} and vwinventory_status.inventory_reference={vwinventory_status.inventory_reference} and vwinventory_status.previous_location={vwinventory_status.previous_location} and vwinventory_status.location_code={vwinventory_status.location_code} and vwinventory_status.standing_hours={vwinventory_status.standing_hours} and vwinventory_status.stock_status={vwinventory_status.stock_status})
main_table_name: stock_items
fields:
 field1:
  field_name:  vwinventory_status.stock_type_code
  caption: stock_type_code
  field_type: lookup
  list: "select distinct stock_type_code from stock_types order by stock_type_code"
 field2:
  field_name: vwinventory_status.previous_location
  caption: previous_location
  field_type: lookup
  list: "select location_code from locations order by location_code"    
 field3:
  field_name: vwinventory_status.location_code
  caption: current_location
  field_type: lookup
  list: "select location_code from locations order by location_code"    
 field4:
  field_name: vwinventory_status.stock_status
  caption: stock_status
  field_type: lookup
  list: "select 'NOT_ON_STOCK' as stock_status union select 'ON_STOCK' as stock_status"  
  
