query: select * from vwinventory_transactions_bins WHERE (stock_type_code={stock_type_code} and inventory_reference={inventory_reference} and transaction_business_name_code={transaction_business_name_code} and location_from={location_from} and location_to={location_to} and created_at={created_at} and farm_code={farm_code} and variety_code={variety_code})
main_table_name: inventory_transactions
fields:
 field1:
  field_name:  stock_type_code
  caption: stock_type_code
  field_type: lookup
  list: "select distinct stock_type_code from stock_types order by stock_type_code"
 field2:
  field_name: transaction_business_name_code
  caption: transaction_business_name_code
  field_type: lookup
  list: "select transaction_business_name_code from transaction_business_names order by transaction_business_name_code"  
 field3:
  field_name: location_from
  caption: location_from
  field_type: lookup
  list: "select location_code from locations order by location_code"    
 field4:
  field_name: location_to
  caption: location_to
  field_type: lookup
  list: "select location_code from locations order by location_code"    
 field5:
  field_name: created_at
  caption: created_at
  field_type: daterange