query: SELECT vwonstock_pallets.season_code, vwonstock_pallets.iso_week_code, vwonstock_pallets.commodity_code,vwonstock_pallets.marketing_variety_code, vwonstock_pallets.fg_code_old,  vwinventory_status.inventory_reference,  vwinventory_status.stock_type_code,  vwinventory_status.location_code,  vwinventory_status.created_on,  vwinventory_status.updated_at,  vwinventory_status.previous_location,  vwinventory_status.standing_hours,  vwinventory_status.destroyed,  vwinventory_status.between_move_hours,  vwinventory_status.stock_status,  vwinventory_status.id,  vwonstock_pallets.date_time_completed,  vwonstock_pallets.rw_create_datetime,  vwonstock_pallets.inspection_date_time,  vwonstock_pallets.age_inspect,  vwonstock_pallets.inspection_level_code,  vwonstock_pallets.inspection_reason,  vwonstock_pallets.process_status,  vwonstock_pallets.qc_result_status,  vwonstock_pallets.date_time_created, vwonstock_pallets.carton_quantity_actual,  vwonstock_pallets.qc_status_code,  vwonstock_pallets.oldest_pack_date_time,  vwonstock_pallets.age_interwarehouse,  vwonstock_pallets.last_interwarehouse_offload_date  FROM vwinventory_status  INNER JOIN vwonstock_pallets ON (vwinventory_status.inventory_reference = vwonstock_pallets.pallet_number) WHERE (vwinventory_status.stock_type_code={vwinventory_status.stock_type_code} and vwinventory_status.inventory_reference={vwinventory_status.inventory_reference} and vwinventory_status.previous_location={vwinventory_status.previous_location} and vwinventory_status.location_code={vwinventory_status.location_code} and vwinventory_status.standing_hours={vwinventory_status.standing_hours} and vwinventory_status.stock_status={vwinventory_status.stock_status} and  vwonstock_pallets.season_code={vwonstock_pallets.season_code} and vwonstock_pallets.commodity_code={vwonstock_pallets.commodity_code} and vwonstock_pallets.marketing_variety_code={vwonstock_pallets.marketing_variety_code})
main_table_name: stock_items
fields:
 field1:
  field_name:  vwinventory_status.stock_type_code
  caption: stock_type_code
  field_type: lookup
  list: "select distinct stock_type_code from stock_types order by stock_type_code"
 field2:
  field_name: vwinventory_status.previous_location
  caption: previous_location
  field_type: lookup
  list: "select location_code from locations order by location_code"    
 field3:
  field_name: vwinventory_status.location_code
  caption: current_location
  field_type: lookup
  list: "select location_code from locations order by location_code"    
 field4:
  field_name: vwinventory_status.stock_status
  caption: stock_status
  field_type: lookup
  list: "select 'NOT_ON_STOCK' as stock_status union select 'ON_STOCK' as stock_status"  
 field5:
  field_name: vwonstock_pallets.season_code
  caption: season
  field_type: lookup
  list: "select distinct season from seasons order by season desc"  
 field6:
  field_name: vwonstock_pallets.commodity_code
  caption: commodity
  field_type: lookup
  list: "select commodity_code from commodities order by commodity_code"    
 field7:
  field_name: vwonstock_pallets.marketing_variety_code
  caption: variety
  field_type: lookup
  list: "select marketing_variety_code from marketing_varieties  order by marketing_variety_code"      
grid_configs:
  column_widths:
  data_types:
    carton_quantity_actual: integer
    age_inspect: integer
    age_interwarehouse: integer
    standing_hours: integer
    between_move_hours: integer
  
  column_captions:
    created_on: first_iw_offload
    updated_at: last_iventory_tran
    carton_quantity_actual: ctn_qty
    date_time_completed: skip_complete
    rw_create_datetime: create_in_reworks
    date_time_created: first_ctn_skip
    last_interwarehouse_offload_date: last_iw_offload