query: select trans_date, current_location, stand_time_hours, previous_trans_date_time, location_from, location_to, transaction_business_name, inventory_reference, stock_type_code, track_slms_indicator_1_code, size_code, product_class_code, treatment_code, variety_code, commodity_code, farm_code,  'row ' || CAST(ROW_NUMBER() OVER() AS character varying) AS id from  vwinventory_stock_status_bin WHERE (vwinventory_stock_status_bin.stock_type_code={vwinventory_stock_status_bin.stock_type_code} and vwinventory_stock_status_bin.inventory_reference={vwinventory_stock_status_bin.inventory_reference} and vwinventory_stock_status_bin.location_from={vwinventory_stock_status_bin.location_from} and vwinventory_stock_status_bin.location_to={vwinventory_stock_status_bin.location_to}  and vwinventory_stock_status_bin.current_location={vwinventory_stock_status_bin.current_location} and stand_time_hours={stand_time_hours} and farm_code={farm_code} and variety_code={variety_code})
main_table_name: inventory_transaction_stocks
fields:
 field1:
  field_name:  vwinventory_stock_status_bin.stock_type_code
  caption: stock_type_code
  field_type: lookup
  list: "select distinct stock_type_code from stock_types order by stock_type_code"
 field2:
  field_name: vwinventory_stock_status_bin.location_from
  caption: location_from
  field_type: lookup
  list: "select location_code from locations order by location_code"    
 field3:
  field_name: vwinventory_stock_status_bin.location_to
  caption: current_location
  field_type: lookup
  list: "select location_code from locations order by location_code"    
 field4:
  field_name: vwinventory_stock_status_bin.current_location
  caption: current_location
  field_type: lookup
  list: "select location_code from locations order by location_code"      
 field5:
  field_name:  vwinventory_stock_status_bin.inventory_reference
  caption: bin_number
  field_type: text