--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: "1.10"
    id: "32"
    disabled: f
    is_non_web_program: t
    display_name: Depot Receipts
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: PrintDepotCtnLabels
      is_leaf: f
      functional_area_name: "1.10"
      technology: 
      id: "229"
      disabled: f
      description: 
      functional_area_id: "32"
      is_non_web_program: t
      display_name: print_depot_ctn_labels
      program_name: 1.10.4
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-09-21 12:05:29
        class_name: PrintDepotCtnLabels
        name: 1.10.4.1
        program_id: "229"
        functional_area_name: "1.10"
        id: "895"
        disabled: f
        description: PrintDepotCtnLabels
        is_non_web_program: t
        display_name: print depot ctn labels
        program_name: 1.10.4
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-09-21 12:06:21
        class_name: PrintCartonSequence
        name: 1.10.4.2
        program_id: "229"
        functional_area_name: "1.10"
        id: "896"
        disabled: f
        description: print depot ctn labels
        is_non_web_program: t
        display_name: print depot ctn sequence
        program_name: 1.10.4
