--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: "1.2"
    id: "29"
    disabled: f
    is_non_web_program: t
    display_name: Inter Warehouse
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: IwLoadVehicle
      is_leaf: f
      url_component: 
      functional_area_name: "1.2"
      technology: 
      id: "338"
      disabled: f
      description: 
      functional_area_id: "29"
      is_non_web_program: t
      display_name: load_vehicle
      program_name: 1.2.1
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2011-08-01 15:48:59
        class_name: 
        name: 1.2.1.5
        program_id: "338"
        functional_area_name: "1.2"
        id: "1113"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: join_load_vehicle_process
        program_name: 1.2.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2011-08-01 14:47:27
        class_name: 
        name: 1.2.1.1
        program_id: "338"
        functional_area_name: "1.2"
        id: "1104"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: load_vehicle
        program_name: 1.2.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2011-08-01 14:53:57
        class_name: 
        name: 1.2.1.2
        program_id: "338"
        functional_area_name: "1.2"
        id: "1105"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: scan_pallet
        program_name: 1.2.1
