--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: "1.2"
    id: "29"
    disabled: f
    is_non_web_program: t
    display_name: Inter Warehouse
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: OffloadVehicle
      is_leaf: f
      url_component: 
      functional_area_name: "1.2"
      technology: 
      id: "339"
      disabled: f
      description: 
      functional_area_id: "29"
      is_non_web_program: t
      display_name: offload_vehicle
      program_name: 1.2.2
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2011-08-01 15:03:30
        class_name: 
        name: 1.2.2.1
        program_id: "339"
        functional_area_name: "1.2"
        id: "1108"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: offload_vehicle
        program_name: 1.2.2
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2011-08-01 15:05:04
        class_name: 
        name: 1.2.2.2
        program_id: "339"
        functional_area_name: "1.2"
        id: "1109"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: validate_pallets
        program_name: 1.2.2
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2011-08-01 15:05:28
        class_name: 
        name: 1.2.2.3
        program_id: "339"
        functional_area_name: "1.2"
        id: "1110"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: list_validated_pallets
        program_name: 1.2.2
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2011-08-01 15:05:41
        class_name: 
        name: 1.2.2.4
        program_id: "339"
        functional_area_name: "1.2"
        id: "1111"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: list_invalidated_pallets
        program_name: 1.2.2
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2011-08-01 15:06:20
        class_name: 
        name: 1.2.2.5
        program_id: "339"
        functional_area_name: "1.2"
        id: "1112"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: join_offload_vehicle_process
        program_name: 1.2.2
