--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: "1.4"
    id: "34"
    disabled: f
    is_non_web_program: t
    display_name: recooling
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: CompleteJob
      is_leaf: t
      functional_area_name: "1.4"
      technology: 
      id: "285"
      disabled: f
      description: 
      functional_area_id: "34"
      is_non_web_program: t
      display_name: complete_job
      program_name: 1.4.4
  - []

