--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: "1.5"
    id: "42"
    disabled: f
    is_non_web_program: t
    display_name: Putaway
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: PutAwayPallet
      is_leaf: t
      functional_area_name: "1.5"
      technology: 
      id: "273"
      disabled: f
      description: 
      functional_area_id: "42"
      is_non_web_program: t
      display_name: put_away_pallet
      program_name: 1.5.1
  - []

