--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: "1.6"
    id: "36"
    disabled: f
    is_non_web_program: t
    display_name: Dispatch
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: TruckArrival
      is_leaf: t
      functional_area_name: "1.6"
      technology: 
      id: "253"
      disabled: f
      description: 
      functional_area_id: "36"
      is_non_web_program: t
      display_name: scan_load_number
      program_name: 1.6.1
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-09-03 12:57:52
        class_name: 
        name: 1.6.1.1
        program_id: "253"
        functional_area_name: "1.6"
        id: "848"
        disabled: f
        description: 
        is_non_web_program: t
        display_name: scan_load_number
        program_name: 1.6.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-09-08 14:29:00
        class_name: 
        name: 1.6.2.4
        program_id: "253"
        functional_area_name: "1.6"
        id: "873"
        disabled: f
        description: 
        is_non_web_program: t
        display_name: show_not_yet_loaded_pallets
        program_name: 1.6.1
