--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: "1.6"
    id: "36"
    is_non_web_program: t
    disabled: f
    display_name: Dispatch
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: LoadTruck
      is_leaf: t
      functional_area_name: "1.6"
      technology: 
      url_component: 
      id: "279"
      functional_area_id: "36"
      is_non_web_program: t
      disabled: f
      description: 
      display_name: load_truck
      program_name: 1.6.2
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: 1.6.2.1
        program_id: "279"
        created_on: 2010-09-07 13:59:49
        functional_area_name: "1.6"
        id: "942"
        is_non_web_program: t
        disabled: f
        display_name: scan_pick_list
        description: 
        url_param: 
        program_name: 1.6.2
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: 1.6.2.2
        program_id: "279"
        created_on: 2010-09-07 14:00:47
        functional_area_name: "1.6"
        id: "943"
        is_non_web_program: t
        disabled: f
        display_name: show_loaded_pallets
        description: 
        url_param: 
        program_name: 1.6.2
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: 1.6.2.3
        program_id: "279"
        created_on: 2010-09-07 14:02:27
        functional_area_name: "1.6"
        id: "944"
        is_non_web_program: t
        disabled: f
        display_name: show_not_yet_loaded_pallets
        description: 
        url_param: 
        program_name: 1.6.2
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: 1.6.2.4
        program_id: "279"
        created_on: 2010-09-08 14:29:00
        functional_area_name: "1.6"
        id: "946"
        is_non_web_program: t
        disabled: f
        display_name: scan_pallet_to_load
        description: 
        url_param: 
        program_name: 1.6.2
