--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: "1.7"
    id: "31"
    disabled: f
    is_non_web_program: t
    display_name: buildup
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: RelabelPallet
      is_leaf: t
      functional_area_name: "1.7"
      technology: ""
      id: "222"
      disabled: f
      description: ""
      functional_area_id: "31"
      is_non_web_program: t
      display_name: relabel_pallet
      program_name: 1.7.6
  - []

