--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: "1.8"
    id: "30"
    disabled: f
    is_non_web_program: t
    display_name: Miscellaneous
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: UnitTempCapture
      is_leaf: t
      functional_area_name: "1.8"
      technology: ""
      id: "218"
      disabled: f
      description: ""
      functional_area_id: "30"
      is_non_web_program: t
      display_name: unit_temp_capture
      program_name: 1.8.6
  - []

