--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: "2.1"
    id: "26"
    disabled: f
    is_non_web_program: t
    display_name: Rmt Receipts
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: ReceiveIntakeBin
      is_leaf: f
      url_component: 
      functional_area_name: "2.1"
      technology: 
      id: "312"
      disabled: f
      description: 
      functional_area_id: "26"
      is_non_web_program: t
      display_name: receive_bins
      program_name: 2.1.1
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-09-16 09:03:52
        class_name: 
        name: 2.1.1.1
        program_id: "312"
        functional_area_name: "2.1"
        id: "1023"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: enter_delivery_number
        program_name: 2.1.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-09-16 09:05:37
        class_name: 
        name: 2.1.1.2
        program_id: "312"
        functional_area_name: "2.1"
        id: "1024"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: scan_full_bins
        program_name: 2.1.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-09-16 09:06:26
        class_name: 
        name: 2.1.1.3
        program_id: "312"
        functional_area_name: "2.1"
        id: "1025"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: scan_half_bins
        program_name: 2.1.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-09-16 09:07:16
        class_name: 
        name: 2.1.1.4
        program_id: "312"
        functional_area_name: "2.1"
        id: "1026"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: complete_delivery
        program_name: 2.1.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-12-13 08:37:34
        class_name: 
        name: 2.1.1.5
        program_id: "312"
        functional_area_name: "2.1"
        id: "1041"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: view_full_bins_scanned
        program_name: 2.1.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-12-13 08:38:17
        class_name: 
        name: 2.1.1.6
        program_id: "312"
        functional_area_name: "2.1"
        id: "1042"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: view_half_bins_scanned
        program_name: 2.1.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-12-13 08:38:57
        class_name: 
        name: 2.1.1.7
        program_id: "312"
        functional_area_name: "2.1"
        id: "1043"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: view_sample_bins_scanned
        program_name: 2.1.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-12-13 08:39:26
        class_name: 
        name: 2.1.1.8
        program_id: "312"
        functional_area_name: "2.1"
        id: "1044"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: scan_intake_bins
        program_name: 2.1.1
