--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: "2.2"
    functional_area_name: "2.2"
    id: "56"
    is_non_web_program: t
    disabled: f
    display_name: rmt interwarehouse
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: PutAwayBin
      is_leaf: t
      functional_area_name: "2.2"
      technology: 
      func_area_url_component: 
      url_component: 
      id: "336"
      functional_area_id: "56"
      is_non_web_program: t
      disabled: f
      description: 
      display_name: putaway_bin
      program_name: 2.2.6
  - []

