--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: "2.2"
    functional_area_name: "2.2"
    id: "56"
    is_non_web_program: f
    disabled: f
    display_name: rmt interwarehouse
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: CreateTripsheetS
      is_leaf: f
      functional_area_name: "2.2"
      technology: 
      url_component: 
      id: "314"
      functional_area_id: "56"
      is_non_web_program: t
      disabled: f
      description: 
      display_name: create_tripsheet
      program_name: 2.2.4
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: 2.2.4.1
        program_id: "314"
        created_on: 2010-12-08 15:33:50
        functional_area_name: "2.2"
        id: "1033"
        is_non_web_program: f
        disabled: f
        display_name: create_tripsheet
        description: 
        url_param: 
        program_name: 2.2.4
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: 2.2.4.2
        program_id: "314"
        created_on: 2010-12-08 15:35:03
        functional_area_name: "2.2"
        id: "1034"
        is_non_web_program: f
        disabled: f
        display_name: print_tripsheet
        description: 
        url_param: 
        program_name: 2.2.4
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: 2.2.4.3
        program_id: "314"
        created_on: 2010-12-08 15:35:47
        functional_area_name: "2.2"
        id: "1035"
        is_non_web_program: f
        disabled: f
        display_name: remove_bin
        description: 
        url_param: 
        program_name: 2.2.4
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: 2.2.4.4
        program_id: "314"
        created_on: 2010-12-08 15:36:24
        functional_area_name: "2.2"
        id: "1036"
        is_non_web_program: f
        disabled: f
        display_name: view_bins_on_tripsheet
        description: 
        url_param: 
        program_name: 2.2.4
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: 2.2.4.5
        program_id: "314"
        created_on: 2010-12-08 15:36:57
        functional_area_name: "2.2"
        id: "1037"
        is_non_web_program: f
        disabled: f
        display_name: scan_bins_on_tripsheet
        description: 
        url_param: 
        program_name: 2.2.4
