--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: "2.2"
    functional_area_name: "2.2"
    id: "56"
    is_non_web_program: f
    disabled: f
    display_name: rmt interwarehouse
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: AcceptBins
      is_leaf: f
      functional_area_name: "2.2"
      technology: 
      url_component: 
      id: "311"
      functional_area_id: "56"
      is_non_web_program: t
      disabled: f
      description: 
      display_name: accept_bins
      program_name: 2.2.1
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: 2.2.1.4
        program_id: "311"
        created_on: 2010-10-04 08:23:48
        functional_area_name: "2.2"
        id: "1027"
        is_non_web_program: f
        disabled: f
        display_name: complete
        description: 
        url_param: 
        program_name: 2.2.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: 2.2.1.1
        program_id: "311"
        created_on: 2010-09-22 11:12:43
        functional_area_name: "2.2"
        id: "1028"
        is_non_web_program: f
        disabled: f
        display_name: scan_location
        description: 
        url_param: 
        program_name: 2.2.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: AcceptBins
        name: 2.2.1.2
        program_id: "311"
        created_on: 2010-10-04 08:20:30
        functional_area_name: "2.2"
        id: "1029"
        is_non_web_program: f
        disabled: f
        display_name: scan_bin
        description: 
        url_param: 
        program_name: 2.2.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: 2.2.1.3
        program_id: "311"
        created_on: 2010-10-04 08:21:08
        functional_area_name: "2.2"
        id: "1030"
        is_non_web_program: f
        disabled: f
        display_name: view_scanned_bins
        description: 
        url_param: 
        program_name: 2.2.1
