--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: Query
    functional_area_name: "2.2"
    id: "27"
    disabled: f
    is_non_web_program: t
    display_name: RMT Interwarehouse
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: AcceptRmtTripsheet
      is_leaf: f
      url_component: 
      functional_area_name: "2.2"
      technology: 
      id: "309"
      disabled: f
      description: 
      functional_area_id: "27"
      is_non_web_program: t
      display_name: accept_tripsheet
      program_name: 2.2.2
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-10-04 11:26:52
        class_name: 
        name: 2.2.2.1
        program_id: "309"
        functional_area_name: "2.2"
        id: "1022"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: scan_tripsheet
        program_name: 2.2.2
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-12-08 15:27:29
        class_name: 
        name: 2.2.2.2
        program_id: "309"
        functional_area_name: "2.2"
        id: "1030"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: complete_prompt
        program_name: 2.2.2
