--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: "2.4"
    id: "38"
    disabled: f
    is_non_web_program: t
    display_name: rmt_receipts
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: ReceiveIntakeBin
      is_leaf: f
      url_component: 
      functional_area_name: "2.4"
      technology: 
      id: "259"
      disabled: f
      description: 
      functional_area_id: "38"
      is_non_web_program: t
      display_name: receive_bins
      program_name: 2.4.1
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-09-16 09:03:52
        class_name: 
        name: 2.4.1.1
        program_id: "259"
        functional_area_name: "2.4"
        id: "875"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: enter_delivery_number
        program_name: 2.4.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-09-16 09:05:37
        class_name: 
        name: 2.4.1.2
        program_id: "259"
        functional_area_name: "2.4"
        id: "876"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: scan_full_bins
        program_name: 2.4.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-09-16 09:06:26
        class_name: 
        name: 2.4.1.3
        program_id: "259"
        functional_area_name: "2.4"
        id: "877"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: scan_half_bins
        program_name: 2.4.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-09-16 09:07:16
        class_name: 
        name: 2.4.1.4
        program_id: "259"
        functional_area_name: "2.4"
        id: "878"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: complete_delivery
        program_name: 2.4.1
