--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: "2.5"
    id: "45"
    disabled: f
    is_non_web_program: t
    display_name: rmt inter warehouse
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: AcceptRmtTripsheet
      is_leaf: f
      url_component: 
      functional_area_name: "2.5"
      technology: 
      id: "291"
      disabled: f
      description: 
      functional_area_id: "45"
      is_non_web_program: t
      display_name: accept_tripsheet
      program_name: 2.5.2
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-10-04 11:26:52
        class_name: 
        name: 2.5.2.1
        program_id: "291"
        functional_area_name: "2.5"
        id: "926"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: scan_tripsheet
        program_name: 2.5.2
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-10-04 11:27:34
        class_name: 
        name: 2.5.2.2
        program_id: "291"
        functional_area_name: "2.5"
        id: "927"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: complete_prompt
        program_name: 2.5.2
