--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: "2.5"
    id: "45"
    disabled: f
    is_non_web_program: t
    display_name: rmt inter warehouse
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: CreateTripSheet
      is_leaf: f
      url_component: 
      functional_area_name: "2.5"
      technology: 
      id: "294"
      disabled: f
      description: 
      functional_area_id: "45"
      is_non_web_program: t
      display_name: create_tripsheet
      program_name: 2.5.4
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-10-12 14:38:45
        class_name: 
        name: 2.5.4.1
        program_id: "294"
        functional_area_name: "2.5"
        id: "936"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: create_tripsheet
        program_name: 2.5.4
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-10-12 14:39:39
        class_name: 
        name: 2.5.4.2
        program_id: "294"
        functional_area_name: "2.5"
        id: "937"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: print_tripsheet
        program_name: 2.5.4
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-10-12 14:40:13
        class_name: 
        name: 2.5.4.3
        program_id: "294"
        functional_area_name: "2.5"
        id: "938"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: remove_bin
        program_name: 2.5.4
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-10-12 14:40:54
        class_name: 
        name: 2.5.4.4
        program_id: "294"
        functional_area_name: "2.5"
        id: "939"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: view_bins_on_trip
        program_name: 2.5.4
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-11-09 12:58:58
        class_name: 
        name: 2.5.4.5
        program_id: "294"
        functional_area_name: "2.5"
        id: "959"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: scan_bins_on_tripsheet
        program_name: 2.5.4
