--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: "2.5"
    id: "45"
    disabled: f
    is_non_web_program: t
    display_name: rmt inter warehouse
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: AcceptBin
      is_leaf: f
      url_component: 
      functional_area_name: "2.5"
      technology: 
      id: "286"
      disabled: f
      description: 
      functional_area_id: "45"
      is_non_web_program: t
      display_name: accept_bins
      program_name: 2.5.1
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-10-04 08:20:30
        class_name: 
        name: 2.5.1.2
        program_id: "286"
        functional_area_name: "2.5"
        id: "923"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: scan_bin
        program_name: 2.5.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-10-04 08:21:08
        class_name: 
        name: 2.5.1.3
        program_id: "286"
        functional_area_name: "2.5"
        id: "924"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: view_scanned_bins
        program_name: 2.5.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-10-04 08:23:48
        class_name: 
        name: 2.5.1.4
        program_id: "286"
        functional_area_name: "2.5"
        id: "925"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: complete
        program_name: 2.5.1
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-09-22 11:12:43
        class_name: 
        name: 2.5.1.1
        program_id: "286"
        functional_area_name: "2.5"
        id: "912"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: t
        display_name: scan_location
        program_name: 2.5.1
