--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: rmt_processing
    id: "21"
    disabled: f
    is_non_web_program: f
    display_name: rmt_processing
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: 
      is_leaf: f
      url_component: 
      functional_area_name: rmt_processing
      technology: 
      id: "307"
      disabled: f
      description: 
      functional_area_id: "21"
      is_non_web_program: f
      display_name: bin_sales
      program_name: bin_order
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-11-25 09:29:50
        class_name: 
        name: new_bin_order
        program_id: "307"
        functional_area_name: rmt_processing
        id: "1014"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: f
        display_name: new_bin_order
        program_name: bin_order
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-11-25 10:51:21
        class_name: 
        name: search_bin_orders_flat
        program_id: "307"
        functional_area_name: rmt_processing
        id: "1015"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: f
        display_name: search_bin_orders_flat
        program_name: bin_order
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-11-26 08:19:48
        class_name: 
        name: current_order
        program_id: "307"
        functional_area_name: rmt_processing
        id: "1016"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: f
        display_name: current_order
        program_name: bin_order
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-11-26 15:13:57
        class_name: 
        name: list_bin_orders
        program_id: "307"
        functional_area_name: rmt_processing
        id: "1017"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: f
        display_name: recent_orders
        program_name: bin_order
