--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: rmt_processing
    id: "33"
    disabled: 
    is_non_web_program: 
    display_name: rmt_processing
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: 
      is_leaf: f
      url_component: 
      functional_area_name: rmt_processing
      technology: 
      id: "318"
      disabled: f
      description: 
      functional_area_id: "33"
      is_non_web_program: 
      display_name: bin_sales
      program_name: bin_sales
  - []

