--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: diagnostics
    id: "6"
    disabled: 
    is_non_web_program: 
    display_name: diagnostics
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: 
      is_leaf: f
      url_component: 
      functional_area_name: diagnostics
      technology: 
      id: "345"
      disabled: f
      description: 
      functional_area_id: "6"
      is_non_web_program: 
      display_name: comparer
      program_name: comparer
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2011-05-31 21:45:30
        class_name: 
        name: view
        program_id: "345"
        functional_area_name: diagnostics
        id: "1112"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: 
        display_name: view
        program_name: comparer
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2011-05-10 11:58:27
        class_name: 
        name: test_comparer_tool
        program_id: "345"
        functional_area_name: diagnostics
        id: "1111"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: 
        display_name: 
        program_name: comparer
