--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: party_manager
    id: "8"
    disabled: 
    is_non_web_program: 
    display_name: party
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: 
      program_name: contact_method
      functional_area_name: party_manager
      id: "114"
      disabled: 
      is_non_web_program: 
      func_area_url_component: 
      description: 
      technology: 
      display_name: contact_methods
      url_component: 
      is_mf: f
      is_leaf: 
      functional_area_id: "8"
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "317"
        name: list_contact_methods
        disabled: 
        is_non_web_program: 
        func_area_url_component: 
        created_on: 
        description: 
        position: 
        display_name: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "318"
        name: search_contact_methods_flat
        disabled: 
        is_non_web_program: 
        func_area_url_component: 
        created_on: 
        description: 
        position: 
        display_name: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "319"
        name: search_contact_methods_hierarchy
        disabled: 
        is_non_web_program: 
        func_area_url_component: 
        created_on: 
        description: 
        position: 
        display_name: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "320"
        name: new_contact_method
        disabled: 
        is_non_web_program: 
        func_area_url_component: 
        created_on: 
        description: 
        position: 
        display_name: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "321"
        name: list_contact_method_types
        disabled: 
        is_non_web_program: 
        func_area_url_component: 
        created_on: 
        description: 
        position: 
        display_name: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "322"
        name: new_contact_method_type
        disabled: 
        is_non_web_program: 
        func_area_url_component: 
        created_on: 
        description: 
        position: 
        display_name: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "323"
        name: find_party_contact_methods
        disabled: 
        is_non_web_program: 
        func_area_url_component: 
        created_on: 
        description: 
        position: 
        display_name: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "324"
        name: add_party_contact_method
        disabled: 
        is_non_web_program: 
        func_area_url_component: 
        created_on: 
        description: 
        position: 
        display_name: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "325"
        name: new_postal_address_type
        disabled: 
        is_non_web_program: 
        func_area_url_component: 
        created_on: 
        description: 
        position: 
        display_name: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "327"
        name: new_postal_address
        disabled: 
        is_non_web_program: 
        func_area_url_component: 
        created_on: 
        description: 
        position: 
        display_name: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "328"
        name: find_postal_addresses
        disabled: 
        is_non_web_program: 
        func_area_url_component: 
        created_on: 
        description: 
        position: 
        display_name: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "329"
        name: search_postal_addresses_hierarchy
        disabled: 
        is_non_web_program: 
        func_area_url_component: 
        created_on: 
        description: 
        position: 
        display_name: find postal addresses
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "330"
        name: add_party_address
        disabled: 
        is_non_web_program: 
        func_area_url_component: 
        created_on: 
        description: 
        position: 
        display_name: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "331"
        name: find_party_address
        disabled: 
        is_non_web_program: 
        func_area_url_component: 
        created_on: 
        description: 
        position: 
        display_name: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "332"
        name: search_parties_postal_addresses_flat
        disabled: 
        is_non_web_program: 
        func_area_url_component: 
        created_on: 
        description: 
        position: 
        display_name: search parties addresses
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "1239"
        name: upload_org_addresses_and_contacts
        disabled: f
        is_non_web_program: 
        func_area_url_component: 
        created_on: 2019-03-13 13:58:17
        description: 
        position: 
        display_name: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "1240"
        name: add_org_address
        disabled: f
        is_non_web_program: 
        func_area_url_component: 
        created_on: 2019-03-13 13:59:08
        description: 
        position: 
        display_name: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        program_id: "114"
        url_param: 
        program_name: contact_method
        functional_area_name: party_manager
        prog_url_component: 
        id: "1241"
        name: list_org_addresses
        disabled: f
        is_non_web_program: 
        func_area_url_component: 
        created_on: 2019-03-13 13:59:39
        description: 
        position: 
        display_name: 
