--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: inventory_facade
    id: "59"
    is_non_web_program: f
    disabled: f
    display_name: 
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: 
      is_leaf: f
      functional_area_name: inventory_facade
      technology: 
      func_area_url_component: 
      url_component: 
      id: "328"
      functional_area_id: "59"
      is_non_web_program: f
      disabled: f
      description: 
      display_name: 
      program_name: facade_test
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        position: 
        class_name: 
        name: create_stock
        program_id: "328"
        created_on: 2011-02-15 10:57:24
        functional_area_name: inventory_facade
        func_area_url_component: 
        id: "1079"
        is_non_web_program: f
        disabled: f
        display_name: 
        description: 
        url_param: 
        prog_url_component: 
        program_name: facade_test
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        position: 
        class_name: 
        name: undo_remove_stock
        program_id: "328"
        created_on: 2011-02-22 11:23:48
        functional_area_name: inventory_facade
        func_area_url_component: 
        id: "1080"
        is_non_web_program: f
        disabled: f
        display_name: 
        description: 
        url_param: 
        prog_url_component: 
        program_name: facade_test
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        position: 
        class_name: 
        name: remove_stock
        program_id: "328"
        created_on: 2011-06-24 14:25:42
        functional_area_name: inventory_facade
        func_area_url_component: 
        id: "1084"
        is_non_web_program: f
        disabled: f
        display_name: 
        description: 
        url_param: 
        prog_url_component: 
        program_name: facade_test
