--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    display_name: party
    id: "8"
    class_name: 
    disabled: 
    functional_area_name: party_manager
    is_non_web_program: 
- - !ActiveRecord,2010/Program 
    attributes: 
      technology: 
      functional_area_id: "8"
      program_name: farm
      func_area_url_component: 
      url_component: 
      display_name: farms
      is_leaf: 
      id: "115"
      class_name: 
      description: 
      is_mf: f
      disabled: 
      functional_area_name: party_manager
      is_non_web_program: 
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        program_name: farm
        func_area_url_component: 
        prog_url_component: 
        created_on: 
        display_name: 
        program_id: "115"
        position: 
        id: "333"
        class_name: 
        description: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        is_non_web_program: 
        name: list_farms
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        program_name: farm
        func_area_url_component: 
        prog_url_component: 
        created_on: 
        display_name: search farms
        program_id: "115"
        position: 
        id: "334"
        class_name: 
        description: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        is_non_web_program: 
        name: search_farms_flat
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        program_name: farm
        func_area_url_component: 
        prog_url_component: 
        created_on: 
        display_name: find farms
        program_id: "115"
        position: 
        id: "335"
        class_name: 
        description: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        is_non_web_program: 
        name: search_farms_hierarchy
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        program_name: farm
        func_area_url_component: 
        prog_url_component: 
        created_on: 
        display_name: 
        program_id: "115"
        position: 
        id: "336"
        class_name: 
        description: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        is_non_web_program: 
        name: new_farm
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        program_name: farm
        func_area_url_component: 
        prog_url_component: 
        created_on: 
        display_name: 
        program_id: "115"
        position: 
        id: "337"
        class_name: 
        description: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        is_non_web_program: 
        name: new_puc_type
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        program_name: farm
        func_area_url_component: 
        prog_url_component: 
        created_on: 
        display_name: 
        program_id: "115"
        position: 
        id: "338"
        class_name: 
        description: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        is_non_web_program: 
        name: list_puc_types
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        program_name: farm
        func_area_url_component: 
        prog_url_component: 
        created_on: 
        display_name: 
        program_id: "115"
        position: 
        id: "339"
        class_name: 
        description: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        is_non_web_program: 
        name: new_puc
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        program_name: farm
        func_area_url_component: 
        prog_url_component: 
        created_on: 
        display_name: find_pucs
        program_id: "115"
        position: 
        id: "340"
        class_name: 
        description: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        is_non_web_program: 
        name: search_pucs_hierarchy
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        program_name: farm
        func_area_url_component: 
        prog_url_component: 
        created_on: 
        display_name: 
        program_id: "115"
        position: 
        id: "341"
        class_name: 
        description: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        is_non_web_program: 
        name: new_farm_group
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        program_name: farm
        func_area_url_component: 
        prog_url_component: 
        created_on: 
        display_name: 
        program_id: "115"
        position: 
        id: "342"
        class_name: 
        description: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        is_non_web_program: 
        name: list_farm_groups
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        program_name: farm
        func_area_url_component: 
        prog_url_component: 
        created_on: 
        display_name: add farm puc
        program_id: "115"
        position: 
        id: "343"
        class_name: 
        description: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        is_non_web_program: 
        name: new_farm_puc_account
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        program_name: farm
        func_area_url_component: 
        prog_url_component: 
        created_on: 
        display_name: find farm pucs
        program_id: "115"
        position: 
        id: "344"
        class_name: 
        description: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        is_non_web_program: 
        name: search_farm_puc_accounts_hierarchy
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        program_name: farm
        func_area_url_component: 
        prog_url_component: 
        created_on: 
        display_name: search farm pucs
        program_id: "115"
        position: 
        id: "345"
        class_name: 
        description: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        is_non_web_program: 
        name: search_farm_puc_accounts_flat
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        program_name: farm
        func_area_url_component: 
        prog_url_component: 
        created_on: 2017-11-20 11:43:02
        display_name: 
        program_id: "115"
        position: 
        id: "1235"
        class_name: 
        description: 
        url_param: 
        disabled: f
        functional_area_name: party_manager
        is_non_web_program: 
        name: current_farm
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        program_name: farm
        func_area_url_component: 
        prog_url_component: 
        created_on: 2019-03-15 14:21:57
        display_name: 
        program_id: "115"
        position: 
        id: "1242"
        class_name: 
        description: 
        url_param: 
        disabled: f
        functional_area_name: party_manager
        is_non_web_program: 
        name: list_cities
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        program_name: farm
        func_area_url_component: 
        prog_url_component: 
        created_on: 2019-03-15 14:35:46
        display_name: 
        program_id: "115"
        position: 
        id: "1243"
        class_name: 
        description: 
        url_param: 
        disabled: f
        functional_area_name: party_manager
        is_non_web_program: 
        name: new_city
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        program_name: farm
        func_area_url_component: party_manager
        prog_url_component: transporter
        created_on: 2019-03-18 10:52:42
        display_name: 
        program_id: "115"
        position: 
        id: "1244"
        class_name: 
        description: 
        url_param: 
        disabled: f
        functional_area_name: party_manager
        is_non_web_program: 
        name: list_transporters
