--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: security
    id: "1"
    disabled: 
    is_non_web_program: 
    display_name: 
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: 
      is_leaf: 
      url_component: 
      functional_area_name: security
      technology: 
      id: "36"
      disabled: 
      description: 
      functional_area_id: "1"
      is_non_web_program: 
      display_name: functional_areas
      program_name: functional_area
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 
        class_name: 
        name: search_functional_areas_flat
        program_id: "36"
        functional_area_name: security
        id: "88"
        disabled: 
        description: ""
        url_param: 
        is_non_web_program: 
        display_name: find
        program_name: functional_area
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 
        class_name: 
        name: new_functional_area
        program_id: "36"
        functional_area_name: security
        id: "90"
        disabled: 
        description: ""
        url_param: 
        is_non_web_program: 
        display_name: ""
        program_name: functional_area
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 
        class_name: 
        name: list_functional_areas
        program_id: "36"
        functional_area_name: security
        id: "87"
        disabled: 
        description: ""
        url_param: 
        is_non_web_program: 
        display_name: ""
        program_name: functional_area
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-10-19 13:28:40
        class_name: 
        name: generate_pdt_menu_structure
        program_id: "36"
        functional_area_name: security
        id: "952"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: 
        display_name: 
        program_name: functional_area
