--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    display_name: inventory
    disabled: f
    class_name: 
    is_non_web_program: f
    functional_area_name: inventory
    id: "25"
- - !ActiveRecord,2010/Program 
    attributes: 
      technology: 
      display_name: 
      disabled: f
      program_name: grouped_assets
      func_area_url_component: 
      url_component: 
      is_leaf: f
      class_name: 
      is_non_web_program: f
      description: 
      functional_area_id: "25"
      functional_area_name: inventory
      id: "303"
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: find_asset_class
        prog_url_component: 
        position: 
        disabled: f
        program_name: grouped_assets
        program_id: "303"
        func_area_url_component: 
        name: search_asset_classes
        url_param: 
        class_name: 
        is_non_web_program: f
        description: 
        functional_area_name: inventory
        id: "1002"
        created_on: 2010-09-23 11:07:33
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: 
        prog_url_component: 
        position: 
        disabled: f
        program_name: grouped_assets
        program_id: "303"
        func_area_url_component: 
        name: new_asset_class
        url_param: 
        class_name: 
        is_non_web_program: f
        description: 
        functional_area_name: inventory
        id: "1003"
        created_on: 2010-09-23 11:06:54
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: stock transaction histories
        prog_url_component: 
        position: 
        disabled: f
        program_name: grouped_assets
        program_id: "303"
        func_area_url_component: 
        name: search_stock_transaction_histories
        url_param: 
        class_name: 
        is_non_web_program: f
        description: 
        functional_area_name: inventory
        id: "1103"
        created_on: 2011-11-27 21:23:19
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: 
        prog_url_component: 
        position: 
        disabled: f
        program_name: grouped_assets
        program_id: "303"
        func_area_url_component: 
        name: search_stock_locations_histories
        url_param: 
        class_name: 
        is_non_web_program: f
        description: 
        functional_area_name: inventory
        id: "1105"
        created_on: 2012-01-13 08:34:25
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: 
        prog_url_component: 
        position: 
        disabled: f
        program_name: grouped_assets
        program_id: "303"
        func_area_url_component: 
        name: reprocess_failed_assets_moves
        url_param: 
        class_name: 
        is_non_web_program: f
        description: 
        functional_area_name: inventory
        id: "1156"
        created_on: 2014-03-12 11:16:44
