--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: rmt_processing
    id: "37"
    is_non_web_program: 
    disabled: 
    display_name: 
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: 
      is_leaf: f
      functional_area_name: rmt_processing
      technology: 
      url_component: 
      id: "297"
      functional_area_id: "37"
      is_non_web_program: 
      disabled: f
      description: 
      display_name: grower grading
      program_name: grower_grading
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: new_grading
        program_id: "297"
        created_on: 2011-01-10 12:51:49
        functional_area_name: rmt_processing
        id: "952"
        is_non_web_program: 
        disabled: f
        display_name: 
        description: 
        url_param: 
        program_name: grower_grading
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: search_pool_graded_summaries_flat
        program_id: "297"
        created_on: 2011-01-12 09:58:37
        functional_area_name: rmt_processing
        id: "953"
        is_non_web_program: 
        disabled: f
        display_name: Find Grading
        description: 
        url_param: 
        program_name: grower_grading
