--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: rmt_processing
    id: "33"
    disabled: 
    is_non_web_program: 
    display_name: rmt_processing
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: 
      is_leaf: f
      url_component: 
      functional_area_name: rmt_processing
      technology: 
      id: "326"
      disabled: f
      description: 
      functional_area_id: "33"
      is_non_web_program: 
      display_name: inter_warehouse
      program_name: inter_warehouse
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2011-01-17 10:42:23
        class_name: 
        name: list_tripsheets
        program_id: "326"
        functional_area_name: rmt_processing
        id: "1063"
        disabled: f
        description: 
        url_param: 
        is_non_web_program: 
        display_name: recent_tripsheets
        program_name: inter_warehouse
