--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: diagnostics
    id: "6"
    disabled: 
    is_non_web_program: 
    display_name: 
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: pdt_log
      is_leaf: f
      functional_area_name: diagnostics
      technology: 
      id: "243"
      disabled: f
      description: 
      functional_area_id: "6"
      is_non_web_program: 
      display_name: pdt logs
      program_name: pdt_log
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-07-06 10:33:02
        class_name: 
        name: find_logs
        program_id: "243"
        functional_area_name: diagnostics
        id: "800"
        disabled: f
        description: 
        is_non_web_program: 
        display_name: find logs
        program_name: pdt_log
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-07-06 10:34:16
        class_name: 
        name: list_pdt_logs
        program_id: "243"
        functional_area_name: diagnostics
        id: "801"
        disabled: f
        description: 
        is_non_web_program: 
        display_name: list pdt logs
        program_name: pdt_log
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-07-06 10:53:43
        class_name: 
        name: last_10_pdt_logs
        program_id: "243"
        functional_area_name: diagnostics
        id: "803"
        disabled: f
        description: 
        is_non_web_program: 
        display_name: last 10 pdt logs
        program_name: pdt_log
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-07-06 10:56:00
        class_name: 
        name: pdt_logs_today
        program_id: "243"
        functional_area_name: diagnostics
        id: "804"
        disabled: f
        description: 
        is_non_web_program: 
        display_name: pdt logs today
        program_name: pdt_log
