--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: diagnostics
    id: "6"
    disabled: 
    is_non_web_program: 
    display_name: 
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: pdt_error
      is_leaf: f
      functional_area_name: diagnostics
      technology: 
      id: "242"
      disabled: f
      description: 
      functional_area_id: "6"
      is_non_web_program: 
      display_name: pdt errors
      program_name: pdt_error
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-07-06 10:12:52
        class_name: 
        name: last_10_pdt_errors
        program_id: "242"
        functional_area_name: diagnostics
        id: "796"
        disabled: f
        description: 
        is_non_web_program: 
        display_name: last 10 pdt errors
        program_name: pdt_error
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-07-06 10:13:53
        class_name: 
        name: pdt_errors_today
        program_id: "242"
        functional_area_name: diagnostics
        id: "797"
        disabled: f
        description: 
        is_non_web_program: 
        display_name: pdt errors today
        program_name: pdt_error
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-07-06 10:25:38
        class_name: 
        name: list_pdt_errors
        program_id: "242"
        functional_area_name: diagnostics
        id: "798"
        disabled: f
        description: 
        is_non_web_program: 
        display_name: list pdt errors
        program_name: pdt_error
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-07-06 10:27:34
        class_name: 
        name: find_errors
        program_id: "242"
        functional_area_name: diagnostics
        id: "799"
        disabled: f
        description: 
        is_non_web_program: 
        display_name: find errors
        program_name: pdt_error
