--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: qc
    id: "51"
    is_non_web_program: f
    disabled: f
    display_name: QC
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: 
      is_leaf: f
      functional_area_name: qc
      technology: 
      url_component: qc_inspection
      id: "296"
      functional_area_id: "51"
      is_non_web_program: f
      disabled: f
      description: 
      display_name: Progressive Defects
      program_name: qc_prog_defs
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: current_qc_business_context_search
        program_id: "296"
        created_on: 2010-12-14 09:49:22
        functional_area_name: qc
        id: "947"
        is_non_web_program: f
        disabled: f
        display_name: Refresh Whatever list
        description: 
        url_param: PROGDEF
        program_name: qc_prog_defs
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: search_inspections
        program_id: "296"
        created_on: 2010-12-14 09:50:55
        functional_area_name: qc
        id: "948"
        is_non_web_program: f
        disabled: f
        display_name: Inspections
        description: 
        url_param: PROGDEF
        program_name: qc_prog_defs
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: current_qc_inspection
        program_id: "296"
        created_on: 2010-12-14 09:51:42
        functional_area_name: qc
        id: "949"
        is_non_web_program: f
        disabled: f
        display_name: Current Inspection
        description: 
        url_param: PROGDEF
        program_name: qc_prog_defs
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: search_business_context
        program_id: "296"
        created_on: 2010-12-01 15:30:37
        functional_area_name: qc
        id: "943"
        is_non_web_program: f
        disabled: f
        display_name: Whatever list
        description: 
        url_param: PROGDEF
        program_name: qc_prog_defs
