--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: qc
    id: "51"
    is_non_web_program: f
    disabled: f
    display_name: QC
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: 
      is_leaf: f
      functional_area_name: qc
      technology: 
      url_component: 
      id: "292"
      functional_area_id: "51"
      is_non_web_program: f
      disabled: f
      description: 
      display_name: Setup
      program_name: qc_setup
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: list_qc_tests
        program_id: "292"
        created_on: 2010-11-25 19:00:43
        functional_area_name: qc
        id: "938"
        is_non_web_program: f
        disabled: f
        display_name: 
        description: 
        url_param: 
        program_name: qc_setup
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: list_qc_inspection_types
        program_id: "292"
        created_on: 2010-11-23 15:09:18
        functional_area_name: qc
        id: "930"
        is_non_web_program: f
        disabled: f
        display_name: 
        description: 
        url_param: 
        program_name: qc_setup
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: search_qc_reasons
        program_id: "292"
        created_on: 2010-11-23 15:09:57
        functional_area_name: qc
        id: "935"
        is_non_web_program: f
        disabled: f
        display_name: 
        description: 
        url_param: 
        program_name: qc_setup
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: search_qc_inspection_types
        program_id: "292"
        created_on: 2010-11-23 15:09:19
        functional_area_name: qc
        id: "931"
        is_non_web_program: f
        disabled: f
        display_name: 
        description: 
        url_param: 
        program_name: qc_setup
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: search_qc_tests
        program_id: "292"
        created_on: 2010-11-25 19:00:43
        functional_area_name: qc
        id: "939"
        is_non_web_program: f
        disabled: f
        display_name: 
        description: 
        url_param: 
        program_name: qc_setup
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: list_qc_reasons
        program_id: "292"
        created_on: 2010-11-23 15:09:57
        functional_area_name: qc
        id: "934"
        is_non_web_program: f
        disabled: f
        display_name: 
        description: 
        url_param: 
        program_name: qc_setup
