--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: production
    id: "11"
    is_non_web_program: 
    disabled: 
    display_name: production
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: 
      is_leaf: 
      functional_area_name: production
      technology: 
      url_component: 
      id: "89"
      functional_area_id: "11"
      is_non_web_program: 
      disabled: 
      description: 
      display_name: ""
      program_name: resources
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: list_bintip_stations
        program_id: "89"
        created_on: 
        functional_area_name: production
        id: "167"
        is_non_web_program: 
        disabled: 
        display_name: ""
        description: ""
        url_param: 
        program_name: resources
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: new_bintip_station
        program_id: "89"
        created_on: 
        functional_area_name: production
        id: "168"
        is_non_web_program: 
        disabled: 
        display_name: ""
        description: ""
        url_param: 
        program_name: resources
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: list_carton_label_stations
        program_id: "89"
        created_on: 
        functional_area_name: production
        id: "169"
        is_non_web_program: 
        disabled: 
        display_name: ""
        description: ""
        url_param: 
        program_name: resources
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: new_carton_label_station
        program_id: "89"
        created_on: 
        functional_area_name: production
        id: "170"
        is_non_web_program: 
        disabled: 
        display_name: ""
        description: ""
        url_param: 
        program_name: resources
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: list_skips
        program_id: "89"
        created_on: 
        functional_area_name: production
        id: "173"
        is_non_web_program: 
        disabled: 
        display_name: ""
        description: ""
        url_param: 
        program_name: resources
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: new_skip
        program_id: "89"
        created_on: 
        functional_area_name: production
        id: "174"
        is_non_web_program: 
        disabled: 
        display_name: ""
        description: ""
        url_param: 
        program_name: resources
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: define_facilities
        program_id: "89"
        created_on: 
        functional_area_name: production
        id: "166"
        is_non_web_program: 
        disabled: 
        display_name: manage facilities
        description: ""
        url_param: 
        program_name: resources
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: list_line_configs
        program_id: "89"
        created_on: 
        functional_area_name: production
        id: "175"
        is_non_web_program: 
        disabled: 
        display_name: list line configs
        description: ""
        url_param: 
        program_name: resources
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: new_line_config
        program_id: "89"
        created_on: 
        functional_area_name: production
        id: "176"
        is_non_web_program: 
        disabled: 
        display_name: ""
        description: ""
        url_param: 
        program_name: resources
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: list_rebin_label_stations
        program_id: "89"
        created_on: 
        functional_area_name: production
        id: "177"
        is_non_web_program: 
        disabled: 
        display_name: ""
        description: ""
        url_param: 
        program_name: resources
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: new_rebin_label_station
        program_id: "89"
        created_on: 
        functional_area_name: production
        id: "178"
        is_non_web_program: 
        disabled: 
        display_name: ""
        description: ""
        url_param: 
        program_name: resources
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: list_pallet_label_stations
        program_id: "89"
        created_on: 
        functional_area_name: production
        id: "179"
        is_non_web_program: 
        disabled: 
        display_name: ""
        description: ""
        url_param: 
        program_name: resources
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        class_name: 
        name: new_pallet_label_station
        program_id: "89"
        created_on: 
        functional_area_name: production
        id: "180"
        is_non_web_program: 
        disabled: 
        display_name: ""
        description: ""
        url_param: 
        program_name: resources
