--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: tools
    id: "20"
    disabled: 
    is_non_web_program: 
    display_name: 
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: 
      is_leaf: f
      functional_area_name: tools
      technology: 
      id: "256"
      disabled: f
      description: 
      functional_area_id: "20"
      is_non_web_program: 
      display_name: shifts
      program_name: shift
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-07-29 21:18:44
        class_name: 
        name: list_shifts
        program_id: "256"
        functional_area_name: tools
        id: "854"
        disabled: 
        description: 
        is_non_web_program: 
        display_name: 
        program_name: shift
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-07-29 21:18:44
        class_name: 
        name: new_shift
        program_id: "256"
        functional_area_name: tools
        id: "857"
        disabled: 
        description: 
        is_non_web_program: 
        display_name: 
        program_name: shift
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-07-29 23:05:29
        class_name: 
        name: search_shifts_flat
        program_id: "256"
        functional_area_name: tools
        id: "858"
        disabled: f
        description: 
        is_non_web_program: 
        display_name: find shift
        program_name: shift
