--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: tools
    id: "20"
    disabled: 
    is_non_web_program: 
    display_name: 
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: 
      is_leaf: 
      functional_area_name: tools
      technology: 
      id: "250"
      disabled: 
      description: 
      functional_area_id: "20"
      is_non_web_program: 
      display_name: shift_types
      program_name: shift_type
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-07-27 21:57:22
        class_name: 
        name: list_shift_types
        program_id: "250"
        functional_area_name: tools
        id: "845"
        disabled: 
        description: 
        is_non_web_program: 
        display_name: 
        program_name: shift_type
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-07-27 21:57:23
        class_name: 
        name: search_shift_types_flat
        program_id: "250"
        functional_area_name: tools
        id: "846"
        disabled: 
        description: 
        is_non_web_program: 
        display_name: 
        program_name: shift_type
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-07-27 21:57:23
        class_name: 
        name: search_shift_types_hierarchy
        program_id: "250"
        functional_area_name: tools
        id: "847"
        disabled: 
        description: 
        is_non_web_program: 
        display_name: 
        program_name: shift_type
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-07-27 21:57:23
        class_name: 
        name: new_shift_type
        program_id: "250"
        functional_area_name: tools
        id: "848"
        disabled: 
        description: 
        is_non_web_program: 
        display_name: 
        program_name: shift_type
