--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    class_name: 
    functional_area_name: inventory
    id: "25"
    disabled: f
    is_non_web_program: f
    display_name: inventory
- - !ActiveRecord,2010/Program 
    attributes: 
      class_name: 
      is_leaf: 
      url_component: 
      functional_area_name: inventory
      technology: 
      id: "317"
      disabled: 
      description: 
      functional_area_id: "25"
      is_non_web_program: 
      display_name: status_types
      program_name: status_type
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        created_on: 2010-12-15 08:56:35
        class_name: 
        name: list_status_types
        program_id: "317"
        functional_area_name: inventory
        id: "1051"
        disabled: 
        description: 
        url_param: 
        is_non_web_program: 
        display_name: 
        program_name: status_type
