--- 
- !ActiveRecord,2010/FunctionalArea 
  attributes: 
    display_name: party
    class_name: 
    disabled: 
    functional_area_name: party_manager
    id: "8"
    is_non_web_program: 
- - !ActiveRecord,2010/Program 
    attributes: 
      display_name: 
      is_leaf: 
      functional_area_id: "8"
      class_name: 
      disabled: 
      url_component: 
      functional_area_name: party_manager
      technology: 
      program_name: trade
      id: "111"
      is_non_web_program: 
      description: 
  - - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: 
        name: new_target_market
        program_id: "111"
        class_name: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        created_on: 
        program_name: trade
        id: "295"
        is_non_web_program: 
        description: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: 
        name: new_mark
        program_id: "111"
        class_name: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        created_on: 
        program_name: trade
        id: "296"
        is_non_web_program: 
        description: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: new inv code
        name: new_inventory_code
        program_id: "111"
        class_name: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        created_on: 
        program_name: trade
        id: "297"
        is_non_web_program: 
        description: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: find target markets
        name: search_target_markets_hierarchy
        program_id: "111"
        class_name: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        created_on: 
        program_name: trade
        id: "298"
        is_non_web_program: 
        description: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: find inv codes
        name: search_inventory_codes_hierarchy
        program_id: "111"
        class_name: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        created_on: 
        program_name: trade
        id: "299"
        is_non_web_program: 
        description: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: find marks
        name: search_marks_hierarchy
        program_id: "111"
        class_name: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        created_on: 
        program_name: trade
        id: "300"
        is_non_web_program: 
        description: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: 
        name: list_destination_countries
        program_id: "111"
        class_name: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        created_on: 
        program_name: trade
        id: "346"
        is_non_web_program: 
        description: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: 
        name: new_destination_country
        program_id: "111"
        class_name: 
        url_param: 
        disabled: 
        functional_area_name: party_manager
        created_on: 
        program_name: trade
        id: "347"
        is_non_web_program: 
        description: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: ""
        name: new_direct_sales_tm
        program_id: "111"
        class_name: 
        url_param: 
        disabled: f
        functional_area_name: party_manager
        created_on: 
        program_name: trade
        id: "730"
        is_non_web_program: f
        description: ""
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: ""
        name: list_direct_sales_tm
        program_id: "111"
        class_name: 
        url_param: 
        disabled: f
        functional_area_name: party_manager
        created_on: 
        program_name: trade
        id: "731"
        is_non_web_program: f
        description: ""
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: list incoterms
        name: list_incoterms
        program_id: "111"
        class_name: 
        url_param: 
        disabled: f
        functional_area_name: party_manager
        created_on: 2012-10-25 15:30:26
        program_name: trade
        id: "1107"
        is_non_web_program: 
        description: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: new incoterm
        name: new_incoterm
        program_id: "111"
        class_name: 
        url_param: 
        disabled: f
        functional_area_name: party_manager
        created_on: 2012-10-25 15:26:45
        program_name: trade
        id: "1106"
        is_non_web_program: 
        description: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: new currency
        name: new_currency
        program_id: "111"
        class_name: 
        url_param: 
        disabled: f
        functional_area_name: party_manager
        created_on: 2012-10-25 16:05:28
        program_name: trade
        id: "1108"
        is_non_web_program: 
        description: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: list currencies
        name: list_currencies
        program_id: "111"
        class_name: 
        url_param: 
        disabled: f
        functional_area_name: party_manager
        created_on: 2012-10-25 16:05:53
        program_name: trade
        id: "1109"
        is_non_web_program: 
        description: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: list trading partners
        name: list_trading_partners
        program_id: "111"
        class_name: 
        url_param: 
        disabled: f
        functional_area_name: party_manager
        created_on: 2012-10-26 10:19:49
        program_name: trade
        id: "1110"
        is_non_web_program: 
        description: 
    - !ActiveRecord,2010/ProgramFunction 
      attributes: 
        display_name: new trading partner
        name: new_trading_partner
        program_id: "111"
        class_name: 
        url_param: 
        disabled: f
        functional_area_name: party_manager
        created_on: 2012-10-26 10:20:18
        program_name: trade
        id: "1111"
        is_non_web_program: 
        description: 
