grading_criteria:
   primary_look_up_field: size
   model_name: PoolGradingSummary
   required_columns: size,grade,variety,line_type,track_slms_indicator_code,new_size,new_class
   csv_header_lines: 0
   total_required_columns: 7
   field_name_mappings:
      size: size
      grade: grade
      variety: variety
      line_code: line_type
      track_indicator: track_slms_indicator_code
      new_size: new_size
      new_class: new_class



