 # ClientSettings.
#
# These are available in code as "ClientSettings.setting_name".
# Settings repeated under the client key ("unifrutti", "stargrow") will override the value in the "defaults" key.
#
# Any new option *must* be set in defaults.
# Only set an option for the client if it differs from the default.
#
# NB *** Do not place comments in lines on their own ***
#        - they will become part of the value of the line above.
#        - ONLY place comments at the end of the line (with a space before the #).
#
defaults: &defaults
  company_name: J&J Multi-Tier
  company_short_name: JMT
  company_long_name: J&J Multi-Tier (Pty) Ltd
  system_email_sender: Packhouse System<jmt@unifrutti.co.za>
  camera_scan_devices:
   - 192.168.50.8
   - 192.168.50.34
  bin_putaway_coldrooms:
    - RA_6TO7_RA_6
    - CA_CDE
    - CA_AB


kromco:
  <<: *defaults
  company_name: Unifrutti
  company_short_name: UD
  company_long_name: KROMCO SOUTH AFRICA (PTY) LTD
  system_email_sender: Kromco system<jmt@kromco.co.za>
  camera_scan_devices:
    - 192.168.50.8
    - 192.168.50.34
  jmt_monitoring_rules:
    edi_out:
      ps_token: ruby
      cmd_token: run_edi_out_proc


