query: select id, production_schedule_id, production_schedule_name, day_line_batch_number, line_id, line_code, shift_id, shift_code, start_date_time, end_date_time, production_run_status, production_run_number, farm_code, account_code, puc_code , production_run_code, applied_sizer_template, production_run_stage, day_line_batch_code, use_alternate_account, batch_code, parent_run_code, child_run_code from production_runs WHERE(start_date_time={start_date_time} and production_schedule_name={production_schedule_name} and line_code={line_code} and farm_code={farm_code} and production_run_code={production_run_code} and parent_run_code={parent_run_code} and child_run_code={child_run_code})
main_table_name: production_runs
fields:
 field1:
  field_name: start_date_time
  caption: start_date_time
  field_type: daterange
 field2:
  field_name: production_schedule_name
  caption: production_schedule_name
  field_type: text
 field3:
  field_name: line_code
  caption: line_code
  field_type: text
 field4:
  field_name: farm_code
  caption: farm_code
  field_type: text
 field5:
  field_name: production_run_code
  caption: production_run_code
  field_type: text
 field6:
  field_name: parent_run_code
  caption: parent_run_code
  field_type: text
 field7:
  field_name: child_run_code
  caption: child_run_code
  field_type: text  