query: select season, variety_code, farm_code, track_indicator_code, commodity_code, production_run_code, product_class_code, id, ripe_point_code, farm_group_code, cold_store_type_code, erp_cultivar, pack_week, line_code from vw_production_run_code WHERE(variety_code={variety_code} and production_run_code={production_run_code} and track_indicator_code={track_indicator_code} and farm_code={farm_code} and commodity_code={commodity_code} and farm_group_code={farm_group_code})
main_table_name: production_runs
fields:
 field1:
  field_name: variety_code
  caption: variety_code
  field_type: text
 field2:
  field_name: production_run_code
  caption: production_run_code
  field_type: text
 field3:
  field_name: track_indicator_code
  caption: track_indicator_code
  field_type: text  
  field4:
   field_name: farm_code
   caption: farm_code
   field_type: lookup
   list: "select farm_code from farms order by farm_code asc"
  field5:
   field_name: commodity_code
   caption: commodity_code
   field_type: lookup
   list: "select commodity_code from commodities order by commodity_code asc"
 field6:
  field_name: farm_group_code
  caption: farm_group_code
  field_type: text  