query: SELECT location_code,location_type_code,location_maximum_units,asset_number,location_quantity,description,id from vw_asset_locations WHERE (vw_asset_locations.location_code={vw_asset_locations.location_code} AND  vw_asset_locations.location_type_code={vw_asset_locations.location_type_code} AND vw_asset_locations.asset_number={vw_asset_locations.asset_number} and vw_asset_locations.location_quantity={vw_asset_locations.location_quantity}) 
main_table_name: locations
fields:
 field1:
  field_name: vw_asset_locations.location_code
  caption: location_code
  field_type: text
 field2:
  field_name: vw_asset_locations.location_type_code
  caption: location_type_code
  field_type: lookup
  list: "select location_type_code from location_types order by location_type_code asc"
 field3:
  field_name: vw_asset_locations.asset_number
  caption: asset_number
  field_type: lookup
  list: "select asset_number from asset_items order by asset_number asc"
 field4:
  field_name: vw_asset_locations.location_quantity
  caption: location_quantity
  field_type: text  

