query: SELECT location_code, location_type_code, asset_number, bin_qty, location_quantity, id, comparison from vw_compare_assets_vs_bin_stock WHERE (location_code={location_code} and location_type_code={location_type_code} and asset_number={asset_number} and comparison={comparison})
main_table_name: asset_locations
fields:
 field1:
  field_name: location_code
  caption: location_code
  field_type: lookup
  list: "select location_code from locations order by location_code asc"
 field2:
  field_name: location_type_code
  caption: location_type_code
  field_type: lookup
  list: "select location_type_code from location_types order by location_type_code asc"
 field3:
  field_name: asset_number
  caption: asset_number
  field_type: lookup
  list: "select asset_number from asset_items order by asset_number asc"
 field4:
  field_name:  comparison
  caption: comparison
  field_type: lookup
  list: "select distinct status_code from statuses where status_type_code = 'comparison' order by status_code"  

